language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 8.0
    - php: 8.0
      env: setup=lowest
    - php: 8.1
    - php: 8.1
      env: setup=lowest
    - php: 8.2
    - php: 8.2
      env: setup=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit
